### ISSUE TITLE
Swift Mailer not compatible with latest WordPress

### ISSUE THREAD

**Issue by nquinlan** [sendgrid/wordpress#12]
_Via sendgrid/docs#513_

<https://sendgrid.com/docs/Integrate/Open_Source_Apps/wordpress.html>

Seem for the SMTP option the plugin depends on the "Swift Mailer" plugin, however it is only compatible up to WordPress 3.5.2, http://wordpress.org/plugins/swift-mailer/.
Not sure if this is the issue but I'm unable to select the SMTP option.

**Comment by hubdotcom** [comment]
Hello, developer of the Swift Mailer WordPress plugin here. It has been updated to support the latest version of WordPress. Please provide any other feedback you have!
