### ISSUE TITLE
Username validation too strict

### ISSUE THREAD

**Issue by mz3** [sendgrid/wordpress#20]
My sendgrid username (email address) contains a + symbol. I cannot use this plugin without first disabling validation. Consider allowing the + symbol in usernames.

**Comment by danielamihalache** [comment]
We will fix this in the next version. Thanks for reporting it.

**Comment by mz3** [comment]
Thanks so much! I'll hold off on updating until then.

**Comment by danielamihalache** [comment]
We have updated the plugin in order to fix this issue.

**Comment by mz3** [comment]
Great! Thanks so much.
