### ISSUE TITLE
 Sendgrid plugin is polluting the Global namespace

### ISSUE THREAD

**Issue by dtwist** [sendgrid/wordpress#24]
> *NOTE: I initially reported this on the WP Plugin support forum for this plugin—I hadn't noticed you had a public repo for it at the time*
> https://wordpress.org/support/topic/sendgrid-plugin-is-polluting-the-global-namespace

Specifically, line 13 of wpsendgrid.php is setting a global variable $plugin:

`$plugin = plugin_basename( __FILE__ );`

As it happens another plugin we're using looks for that variable name, assuming it was set in the WP loop that loads plugins. (We'll be reporting that as a defect to them as well, of course :) ). However, since we're actually loading both Sendgrid and this other plugin as network-wide plugins (loaded in a different loop), the $plugin variable is present because it was instantiated in the Sendgrid plugin... Boom, Crash, etc. :)

Simply removing that definition on line 13 and passing the value directly on line 60 resolves the issue:
currently :
`new Sendgrid_Settings( $plugin );`

becomes:
`new Sendgrid_Settings( plugin_basename( __FILE__ ) );`

Full diff:
```
--- /sendgrid-email-delivery-simplified/wpsendgrid.php
+++ /sendgrid-email-delivery-simplified/wpsendgrid.php (unsaved)
@@ -9,8 +9,6 @@
 Text Domain: sendgrid-email-delivery-simplified
 License: GPLv2
 */
-
-$plugin = plugin_basename( __FILE__ );

 if ( version_compare( phpversion(), '5.3.0', '<' ) ) {
   add_action( 'admin_notices', 'php_version_error' );
@@ -57,7 +55,7 @@
   require_once plugin_dir_path( __FILE__ ) . '/lib/class-sendgrid-smtp.php';

   // Initialize SendGrid Settings
-  new Sendgrid_Settings( $plugin );
+  new Sendgrid_Settings( plugin_basename( __FILE__ ) );

   // Initialize SendGrid Statistics
   new Sendgrid_Statistics();
```

**Comment by danielamihalache** [comment]
This will be added in the next version. Thanks for reporting it!

**Comment by danielamihalache** [comment]
FYI the new plugin version is out, with this change in it. Thanks again for your feedback!

**Comment by natejacobson** [comment]
Great work, @danielamihalache, getting this issue resolved so quickly! Thanks for helping SendGrid be a good WordPress citizen.
