### ISSUE TITLE
Cannot use object of type WP_Error as array

### ISSUE THREAD

**Issue by homebysix** [sendgrid/wordpress#30]
I'm receiving an intermittent error when using SendGrid's WP plugin on one of my sites:

> Fatal error: Cannot use object of type WP_Error as array in ~/public_html/wp-content/plugins/sendgrid-email-delivery-simplified/lib/sendgrid/class-sendgrid-api.php on line 52

Seems to point to [this line](https://github.com/sendgrid/wordpress/blob/4089b8f10498d33f40465d918f45fb12a621e04c/lib/sendgrid/class-sendgrid-api.php#L52), which was added relatively recently. Previous PR #19 seems to have solved an identical problem in the past, so I'm submitting #29 for your consideration.

**Comment by danielamihalache** [comment]
Thanks for your contribution, this was added in the current version.
