### ISSUE TITLE
Sending bulk email, hiding to address

### ISSUE THREAD

**Issue by clarkd** [sendgrid/wordpress#32]
Is it possible to send an email to a list of recipients, but hide these from each other. Using the SendGrid API this is achieved using the X-SMTPAPI header but I can't see an obvious way of doing this via wp_mail().

**Comment by danielamihalache** [comment]
Hi, we will add this functionality also in wp_mail() in the next version of Sendgrid Wordpress plugin.

**Comment by clarkd** [comment]
That's awesome, thank you :)

**Comment by danielamihalache** [comment]
Hi Clark, we have added the the new version the ability to have and individual email sent to each recipient by setting 'x-smtpapi-to' in headers:
Example:
x-smtpapi-to: address1@sendgrid.com,address2@sendgrid.com
