### ISSUE TITLE
Defining SendGrid API Key in WP config Returns - API Key is empty.

### ISSUE THREAD

**Issue by shackep** [sendgrid/wordpress#33]
When I have the API Key defined in wp-config.php and save the SendGrid settings I get a message saying that API Key is empty. All of the other values defined in wp-config are working.
When I use the same API Key via the settings GUI it works.

define('SENDGRID_API_KEY', 'SG.APIKEY');

**Comment by shackep** [comment]
When I add the API Key via settings I can see it in the DB options table as sendgrid_api_key. When I add it via wp-config.php I see that the value is removed from the DB.

**Comment by sebastianplesciuc** [comment]
We're looking into this. Thank you for reporting it.

**Comment by sebastianplesciuc** [comment]
This has been fixed in the latest update, version `1.9.0`. If you still experience this issue, let us know and we'll reopen this thread.

Thank you for reporting it.
