### ISSUE TITLE
PHP 7 Compatibility

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/wordpress#44]
Please see: https://github.com/sendgrid/sendgrid-php/issues/357#issuecomment-282416402

**Comment by sebastianplesciuc** [comment]
@thinkingserious This issue was addressed in this support thread on the Wordpress website: https://wordpress.org/support/topic/php7-compatible-19/

At this time this plugin does not officially support PHP 7. It is in our backlog though and we'll have this in a future version.

**Comment by codesman** [comment]
According to the PHP 7 Compatibility Checker, this plugin is compatible with PHP 7.0 after #47 is merged or if you just add the tags yourself.  I just ran the checker on my site that is running PHP 7.0.11 and get this:

![screen shot 2017-04-17 at 3 38 44 pm](https://cloud.githubusercontent.com/assets/1653589/25107790/67d6368a-2386-11e7-9444-16eed1a2ae8e.png)

**Comment by sebastianplesciuc** [comment]
@codesman Thanks. We'll be looking into you pull request. However we think this might need more testing since some users that did in fact use the plugin in a PHP 7 installation experienced some odd behavior on the settings page. We need to test all plugin functionality using PHP 7. This might take more time.

**Comment by codesman** [comment]
Fair enough!  I'll be implementing this plugin on 5+ PHP 7.0/7.1 sites in the next month or so.  Will definitely report if I find any issues.

**Comment by sebastianplesciuc** [comment]
Hello @codesman

We've tested the plugin on PHP versions 7.0 and 7.1. In the latest version we've merged and included your contribution.
We have also removed some legacy code that has caused some warnings for PHP 7 to some users.

Please let us know if you have any issues either here or on the plugin support forum.

Thank you!
