### ISSUE TITLE
Doesn't work with emails send from Event Organiser

### ISSUE THREAD

**Issue by shankiesan** [sendgrid/wordpress#52]
I'm using Event Organiser Pro to manage events on a number of sites, and it doesn't seem to like sending mails through SendGrid. On all sites, SendGrid sends fine on its own, and so does EO (if SendGrid isn't installed). However, confirmation emails from EO don't send if SendGrid is installed. 

In addition, WP Mail Logger shows the emails as being sent – but they don't ever appear in the SendGrid dashboard, either under 'activity' or any of the failures – making diagnosis rather hard.

Here's the relevant code from `/includes/email.php`:

```
function eventorganiser_mail( $email, $subject, $body, $headers = array(), $attachments = array(), $template = 'none' ) {

        /**
         * @ignore
         */
        //$header = apply_filters( 'eventorganiser_email_body_header', '<html><head><style type="text/css">#outlook a{padding: 0;}</style></head><body>' );
        /**
         * @ignore
         */
        //$footer = apply_filters( 'eventorganiser_email_body_header', '</body></html>' );
        //add_filter( 'wp_mail_content_type', 'eventorganiser_email_html_content_type' );

        if ( $template && 'none' != $template ) {
                /**
                 * @ignore
                 */
                //$body = apply_filters( 'eventorganiser_email_template', $body, $template );
        }

        /* And send! */
        $send = wp_mail( $email, $subject, $header.$body.$footer, $headers, $attachments );

        remove_filter( 'wp_mail_content_type', 'eventorganiser_email_html_content_type' );

        return $send;
}


/**
 * Sets email content type to HTML
 *
 * Hooked onto `wp_mail_content_type` inside `eventorganiser_mail` and removes itself.
 *
 * @since 1.0
 * @see eventorganiser_mail()
 * @access private
 * @ignore
 *
 * @return string 'text/HTML'
 */
function eventorganiser_email_html_content_type() {
        return "text/html";
}
```

**Comment by sebastianplesciuc** [comment]
Hi.

Unfortunately we can't test for that plugin since it's closed source. If you encounter errors because of it, it might be more prudent to contact that plugin author. Since it may be possible that it's causing issues with all mail sending plugins, not just SendGrid.

**Comment by shankiesan** [comment]
I've been working with the plugin author @stephenharris – he might be willing to provide a copy of the source to you directly @sebastianplesciuc so that you can test it. Stephen, would you be keen to do that?

**Comment by sebastianplesciuc** [comment]
Hi.

We're open to this proposal and willing to test and debug this issue. We've added a story to test this in our backlog. From what you said we understood that you have the Pro version installed. Is there a Free version? Does the same issue reproduce with the free version?

We found this repository https://github.com/stephenharris/Event-Organiser We may not need access to the Pro version if this issue can be replicated on the Free version.

**Comment by shankiesan** [comment]
Great, really glad to hear that.

That's the right repo, however, I don't think that the free version does any emailing as it doesn't allow you to book on to any events – the Pro version is what enables booking.

**Comment by stephenharris** [comment]
Happy to provide the source code for Pro, or @shankiesan can if he has a contact email. If not just let me know where I can get in touch.

As noted the plugin uses `wp_mail()`. The body contains HTML and the content type of the email is set accordingly. There are no attachments (by default). The reply-to and from headers a set. Apart from that, nothing different from standard uses of `wp_mail()`.

**Comment by sebastianplesciuc** [comment]
Hello.

This might no longer be necessary since this issue was reported by users that use other plugins as well. Contact Form 7 and WooCommerce for example. We haven't been able to replicate the issue entirely, we think it might be a configuration issue.

The old way of sending emails using API v2 is still in place for SMTP sending in the latest version of the plugin. Can you please check if it works with SMTP?

If you use the same email address for `from` and `to`/`cc`/`bcc`, you might not see the message in your inbox. Particularly if you use a Gmail inbox, emails that have the same `from` and `to` are immediately classified as Spam. Did you check the spam folder?

**Comment by shankiesan** [comment]
Ok, in a way, I'm glad to hear that it's not just us 😄 

Unfortunately I can't easily test sending via SMTP because, to some extent, that's why I'm using SendGrid in the first place – I run all my sites in containers using the official WP Docker image, which doesn't include php_mail – and it's not totally straightforward to add it.

Having said that – does the plugin include its own SMTP client? If so then yes I could give that a go.

**Comment by shankiesan** [comment]
Err yes it looks like Swiftmailer is required for SMTP. I could look into installing it if there's going to be a a long wait until the Rest API method gets sorted, but I assume you guys are going to be looking at it pretty quickly if WPCF7 and WooCommerce aren't working 😃

**Comment by sebastianplesciuc** [comment]
@shankiesan We tested using WPCF7 and WooCommerce and we've been unable to replicate the issue. Our main suspicion is that the users that have reported this issue might suffer from a configuration error which we're trying to pinpoint. However since we can't replicate it, we need the users that are experiencing it to do some small tests to help us get more information to fix it.

We have also tested both SMTP and API sending from a Docker container and it works, with both plugins mentioned above installed.

By looking at the code that you posted we see no apparent reason of why it might not work. Can you send an email to the admin address from the test form on the settings page? If so it might be an issue with the way the `eventorganiser_mail` function gets called, and it's arguments. Maybe the admin email gets mangled somehow, or it contains Unicode characters.

Another way to check it would be installing the Query Monitor plugin and checking to see if there are any errors or warnings during email sending.

**Comment by shankiesan** [comment]
Hi there @sebastianplesciuc  – sorry about the delay, I'v been on holidays 🇯🇵  !!

I can indeed send emails from the test form on the settings page. According to @stephenharris , the only thing that might be causing issues is that EO sends as HTML – but this shouldn't be an issue, should it?

I'll install Query Monitor now and see how I get on. I love QM, but from memory it can sometimes be a bit tricky to diagnose stuff that isn't directly part of a render!

**Comment by sebastianplesciuc** [comment]
Hi.

Hope you had a great holiday.

I don't believe HTML sending might cause this. It may be more of an issue with the email headers (from, to, replyto, etc.).

QM should be able to provide more info on this. You should see a failed HTTP call with a failed status code, maybe even a response.

**Comment by shankiesan** [comment]
Ah, ok, so this is interesting. Query Monitor was useful – if I send an email through SG settings, I get 4 HTTP requests from the SG plugin (as expected). But if I send the mail through confirming an event on EO, I don't get _any_ HTTP requests.

Does that help you at all?

**Comment by stephenharris** [comment]
@shankiesan When you do that, the e-mail is sent and you are redirected back to the page (as part of [PRG pattern](https://en.wikipedia.org/wiki/Post/Redirect/Get)). Query Monitor will show you details of the _current_ request (i.e. the redirect) which didn't send the e-mail.

I think https://wordpress.org/plugins/core-control/ might be a better option as the HTTP logs it makes look like they persist. It requires SG to have used the `wp_remote_*` API, however. (I've not used it myself, just going on what Google tells me).

**Comment by shankiesan** [comment]
Ah that makes sense @stephenharris – in fact, in the back of my head, I had that in mind as why it might not work with QM.

A quick glance shows `wp_remote_post` calls in this plugin, so I'll have a squizz at Core Control and see what I can find out.

**Comment by shankiesan** [comment]
Great shout @stephenharris . Core control worked a treat.

@sebastianplesciuc – here's a screenshot of the output of Core Control. All the 200s are the ones generated by using the SG Settings screen. The 401s are the ones as a result of an EO email.

Any ideas?

**Comment by sebastianplesciuc** [comment]
@shankiesan Sorry, I can't see the screenshot link. `401` you typically get when either credentials are wrong (i.e. `Authorization` header is missing or wrong) or you have IP Access Management on your account and have not added the sending server's IP. Or, more commonly, the API Key you are using does not have email send permissions.

**Comment by shankiesan** [comment]
Oopsy-do @sebastianplesciuc . Here it is:

![image](https://cloud.githubusercontent.com/assets/2608862/26176803/5b9265de-3b4f-11e7-9844-69c94a7cc9ae.png)

Yes, it obviously does suggest a problem with auth; however, as I've mentioned before, this works without issue on this site sending from the SendGrid settings – or WP password reset for that matter.

As you say, it could be something to do with the headers. Here's a successful header from the settings page:

```
    [Content-Type] => application/json
    [User-Agent] => sendgrid/wordpress;php
    [Authorization] => Bearer SG._IB-SdL6S7icH.....[redacted]
```

and an unsuccessful request from EO:

```
    [Content-Type] => application/json
    [User-Agent] => sendgrid/wordpress;php
    [Authorization] => Bearer 
```

So – it's quite obvious from that that the token isn't being sent in the second case. Any ideas why that might be the case? I can't imagine why EO's code would modify the Auth header, can you @stephenharris ?

**Comment by stephenharris** [comment]
No, there's nothing that would do that. 

From what I can see the `POST` request originates from `Sendgrid_API::send()`. The API key is stored in a private variable by the class' constructor. So at the point of instantiation either `$username` is not `api` or the `$password_or_apikey` is empty.

Instantiation happens here: https://github.com/sendgrid/wordpress/blob/af9716f540b7d9a494647dd7713bb0b039ffdd13/lib/sendgrid/class-sendgrid-php.php#L12-L30, so I would put error logs in to see what the value are, and work backwards from there.

e.g. you can trace the origin of those values back to `Sendgrid_Tools::get_sendgrid_option()` or a constant (if defined). 

Maybe worth defining `SENDGRID_SEND_METHOD` and  `SENDGRID_API_KEY` in your `wp-config.php`?

**Comment by sebastianplesciuc** [comment]
I would definitely try the setting the constants to see if the issue replicates.

At first glance maybe there's an issue getting the option from the database.

I forgot to ask, are you using this plugin in a multisite installation?

**Comment by shankiesan** [comment]
Hmm. I already had `SENDGRID_API_KEY` defined in wp-config and have since added `define("SENDGRID_SEND_METHOD", "api");` – and had the same results. No token added to the Auth header, and of course, 401.

@sebastianplesciuc – no, single site install here.

**Comment by sebastianplesciuc** [comment]
I believe this means that `wp-config.php` is not loaded in the place where `wp_mail` is called.

**Comment by shankiesan** [comment]
Ah that's an interesting thought... however, isn't wp-config.php pretty much first in the stack for WordPress? After all, it itself loads `wp-settings.php`... so this should always be before plugins are loaded.

**Comment by stephenharris** [comment]
E-mails in EO are sent from within WordPress (and quite late, using a `load-` hook), there's no reason why `wp-config.php` shouldn't be loaded. Indeed if that were the case your plugins would not have been loaded as that is only possible if there's a database connection (unless you've installed it in `mu-plugins`). I think the best way forward is to use `error_log()` or `xdebug` to walkthrough the execution, logging when the constants are set and when they are used.

One possibility is that the header is modified *after* SG sets it. One way to rule that out is to log the value `$this->apikey` when the `wp_remote_post` is sent. This does seem unlikely though as it looks exactly a like `$this->apikey` is null / empty.

**Comment by shankiesan** [comment]
(I've not loaded it using mu-plugins).

Oh gawd... `xdebug`.  I don't have my current editor set up with xdebug and am not going to get the time to do it any time soon – I'm not doing loads of PHP dev at the moment.

@sebastianplesciuc – any thoughts? I'm assuming that you're reasonably well set up for this!

**Comment by sebastianplesciuc** [comment]
Unfortunately, I don't have the means and the possibility to try to replicate this issue at this time. Another way you could test this is if you remove the constants and add the API key on the settings page, if this truly is a `wp-config.php` issue. But as @stephenharris pointed out, this is less likely to be the case.

As he said, either the value of `this->apikey` is somehow lost, or something hijacks the `wp_remote_post` before it's sent out. Some `error_log`s or `var_dump`s around [here](https://github.com/sendgrid/wordpress/blob/master/lib/sendgrid/class-sendgrid-api.php#L31) might shed more light.

**Comment by shankiesan** [comment]
Oooooooh thanks for the tips, chaps.

The problem is when the API key is set in `wp-config.php` – if I set it in the admin settings screen*, it's all good! I'm happy for this client to crack on with this for now, but it would still be worth investigating the underlying cause. 

*which I never normally do as I bake the API key into the upstream internal WP Docker image that I use for all my clients

**Comment by stephenharris** [comment]
Where in the `wp-config.php` have you put the constants? If it's the very bottom that would explain why they are not set when the e-mail is sent. Otherwise, I cannot see how those constants would not be not be defined at that point.

**Comment by shankiesan** [comment]
Ahhhh ok. So should they be before `require_once(ABSPATH . 'wp-settings.php');` ? In that case, operator error! 

@sebastianplesciuc it might be worth noting in the readme that any sendgrid constants should be defined before requiring wp-settings.php
